### ISSUE TITLE
Is `./tmp/` dir packaged on a purpose?

### ISSUE THREAD

**Issue by ChALkeR** [chbrown/npm-ui#1]
_Notice: I am not a user of this package, this was found during mass npm packages downloading._

Atm, your npm package installed size is **122 MB**, from which **118 MB** (97%) resides in the `./tmp/` dir.
If that is done accidently, you should probably include that dir to `.gitignore` and/or `.npmignore`.

**Comment by chbrown** [comment]
Thanks for the note! Yes, I didn't notice for a while that npm doesn't read my `~/.gitignore_global` file, and hadn't since republished. Fixed in `0.4.6`.

(FWIW, these days I just use `CVS/` instead of `tmp/` -- ugly but it works)
